[project]
name = "scheduler"
version = "0.1.0"
description = "Schedule notification Discord bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py>=2.5.2",
    "python-dotenv>=1.1.1",
]
